spring.application.name=guess-the-character

spring.datasource.url=jdbc:mysql://localhost:3306/guess_character
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true